### ISSUE TITLE
Add the code of conduct to website

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/public-website-content#12]
it's on all our repos, but i need a way to cite it publicly: https://github.com/nih-cfde/organization/blob/master/CODEOFCONDUCT.md

It can just be a link in the footer I think

**Comment by kloydrti** [comment]
The code of conduct now has a page at [https://nih-cfde.org/code-of-conduct/](https://nih-cfde.org/code-of-conduct/) and there is a link to it in the footer.
