### ISSUE TITLE
Use cases in the public site

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/public-website-content#13]
I think right now we have some old, static use cases in the site, but we need to update to using the new use case website. 

Whats the best way to integrate that content? just a link? make the use case repo a sub-module to the main site and let it live in a tab?

**Comment by ACharbonneau** [comment]
forgot to tag @kloydrti

**Comment by alexwaldrop** [comment]
I'll be taking a closer look at this in the next 2-3 days. Keep you posted.

**Comment by ACharbonneau** [comment]
I think for this we should remove the old use cases from the current website (from under resources) and figure out where the final site will live once @ctb has the autogeneration worked out and we know what it looks like

**Comment by kloydrti** [comment]
I removed the 3 use cases from the resources page.
