### ISSUE TITLE
website- Use cases

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/public-website-content#14]
Just adding info/context/parameters for the use case website we discussed.

Current version is here: https://nih-cfde.github.io/usecases/

We are looking for a site format that will *automatically* interlink things, as currently, I hand wrote all those web links and that's terrible. 

Right now, we are building a series of spreadsheets from the website, but *in an ideal world* we want the new site to _populate itself_ from the spreadsheets: https://docs.google.com/spreadsheets/d/19JLmm9LNqaDQU8hgryqHob2RXHgD8-B4QX2v6hQCydE/edit#gid=2033882150

The timeline on this is: It would be amazing if we could have the new website minimally launched by the end of May. 

Please advise on whether that timeline is achievable, and with whether you can create an auto-populated website like that, or if we need to re-think.

**Comment by ACharbonneau** [comment]
@ctb is working on some code to autobuild the yaml we need

**Comment by marisalim** [comment]
Hi - I noticed the "Use Case Library" button on the https://www.nih-cfde.org/ home page goes to the old UCL website. The new website is https://use-cases.nih-cfde.org/.

**Comment by marisalim** [comment]
@kloydrti the "Use Case Library" button on the https://www.nih-cfde.org/ home page goes to the old UCL website (now broken link). The new website URL is: https://use-cases.nih-cfde.org/

**Comment by ACharbonneau** [comment]
i updated it
