### ISSUE TITLE
Modify public website

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/public-website-content#16]
Placeholder for the requirements for the public website update:

- [x] - home page [mockup](https://github.com/nih-cfde/public-website-content/files/4601522/Landing.Page.Basic.Wireframe.1.pdf)
- [x] - website [site map](https://docs.google.com/document/d/1WGQq0b66cWSqSPMLneeixc5EiAe4vkc2t_OyKB4tPeo/edit#bookmark=id.e5on0rsfnmm)
- [x] - potential color palettes 
[CFDE-Palettes.pdf](https://github.com/nih-cfde/public-website-content/files/4616348/CFDE-Palettes.pdf)

**Comment by RLC-DCPPC** [comment]
[Landing Page Basic Wireframe (1).pdf](https://github.com/nih-cfde/public-website-content/files/4601522/Landing.Page.Basic.Wireframe.1.pdf)

**Comment by RLC-DCPPC** [comment]
Actions from 5/26 meeting:

Next steps
    - Bob/Anup to seek further review and provide guidance for the remaining pages
    - Katie to make Wordpress account for Bob
    - Katie to stub out the iFrame link concept

**Comment by RLC-DCPPC** [comment]
Hi @kloydrti .

We owe you 4 URLS for the new public marketing website:

- [ ] Landing page for CFDE UI (we believe this will be https://app.nih-cfde.org/, but will confirm)
- [ ] readthdocs documentation (Amanda is still working on this one)
- [x] training page: that one is [here](https://cfde-training.readthedocs.io)
- [ ] A graphic to replace the placeholder map you currently have

Also, we decided that the bluehost site will be find for the demo dry-run on the 17th, but we need the site to be on nih-cfde.org for the actual demo on the 22nd.  We can discuss this at our meeting on Tuesday, but it seems to me we need to be able to have someone else handle this while you are on PTO.

**Comment by ACharbonneau** [comment]
Will the marketing site also have the new style by the demo? I'm not sure whether I'm supposed to re-skin mine now, or wait.

**Comment by RLC-DCPPC** [comment]
I think we'd like it to have the new style. @kloydrti, do you think we can accomplish that? It'd need to be this week.

**Comment by kloydrti** [comment]
So you want me to go ahead and change the colors on the live nih-cfde.org site? But not the content yet?

**Comment by RLC-DCPPC** [comment]
Oops, I think it can wait a bit longer, since you're still here next week. We'll discuss on Tuesday.

But, yes, @ACharbonneau , I think you can reskin your readthedocs site when you have time ;-) I'm still waiting to get my hands on the credit card, but we should be able to get our subscription next week sometime.

**Comment by ACharbonneau** [comment]
Use case library is moved and reskinned: https://cfde-usecases.readthedocs-hosted.com/en/latest/ please update link accordingly.

**Comment by ACharbonneau** [comment]
Is the logo changing color or staying as is?

**Comment by RLC-DCPPC** [comment]
We like the green and blue logo to match the new buttons.

**Comment by ACharbonneau** [comment]
documentation site: https://cfde-published-documentation.readthedocs-hosted.com/en/latest/

**Comment by kloydrti** [comment]
@ACharbonneau the new logo files are in the CFDE Everyone drive under [CFDE Logos and Templates](https://drive.google.com/drive/folders/14dOaf7-G4k7rCw5mL2Q5jdRWXrO0Y5i-) (web-sized logos are in the web folder)

**Comment by kloydrti** [comment]
The buttons we currently have are:
1. Data Portal
2. C2M2
3. Use Case Library
4. Training
5. Tools

Should C2M2 be changed to Documentation with the documentation site link?

**Comment by ACharbonneau** [comment]
I believe that C2M2 should read "Technical Documentation" and link to the documentation site. Tools will lead to [the internal pages](https://www.nih-cfde.org/products/) with more public friendly documentation, currently all that's there is the C2M2, which I have to update.

**Comment by victor73** [comment]
@RLC-DCPPC  Just asked for access to pull the favicon. Or, perhaps someone could just an accessible URL to it here.

**Comment by kloydrti** [comment]
The logo and icons are available in the [Google Drive logos folder](https://drive.google.com/drive/folders/1XytxvJHTOVpfQ0dFhowFFHPcYFHxNEfm).

**Comment by victor73** [comment]
> @victor73 The logo and icons are available in the [Google Drive logos folder](https://drive.google.com/drive/folders/1XytxvJHTOVpfQ0dFhowFFHPcYFHxNEfm).

Thanks @kloydrti, just waiting for whoever controls that to grant me access...

**Comment by kloydrti** [comment]
@victor73  Oh, you meant access to the drive, not access to the staging site. My mistake.

**Comment by kloydrti** [comment]
![cropped-CFDE_Icon-web-32x32](https://user-images.githubusercontent.com/48324951/84515541-a0be7980-ac9a-11ea-934d-406b09fecf5f.png)
![cropped-CFDE_Icon-web-192x192](https://user-images.githubusercontent.com/48324951/84515542-a1571000-ac9a-11ea-9e0d-6f515ebe16fb.png)
@victor73  Maybe this will work?

**Comment by victor73** [comment]
Okay, the more greenish version is now the favicon on app.nih-cfde.org.

**Comment by ACharbonneau** [comment]
@victor73  You have access to the drive. It's just the CFDE google space. Likely you're trying to log in with an account different from the one you gave us for onboarding

**Comment by RLC-DCPPC** [comment]
Hi @kloydrti . Please change out the static image on the home page with this one:

![export (1)](https://user-images.githubusercontent.com/40363469/84820878-426dff80-afe8-11ea-9b9c-ccd7c11974f2.png)
