### ISSUE TITLE
Updated language about RFCs

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/public-website-content#20]
@RLC-DCPPC @kloydrti 

Hi there! The NIH has changed the way the FOA works, so we need to update https://nih-cfde.org/engagement/ relatively quickly. They changed it a couple weeks ago, but just sent me the updated wording today.

I think we can just replace all of the text AND the table of dates in that tab with this:

[Guidance for Proposers_final.docx](https://github.com/nih-cfde/public-website-content/files/4691889/Guidance.for.Proposers_final.docx)

and then put the

> The Common Fund Data Ecosystem Coordinating Center is looking forward to working with all of you, and we encourage you to reach out to Amanda or Owen at the Coordinating Center, or to describe your ideas to the slack channel so we can help identify other groups that may have a common interest. 

and link to the `Full Engagement Opportunity Announcement` at the end

**Comment by RLC-DCPPC** [comment]
Okay. I'll work on this today. As I understand it, I can just update a file on the GH repo and then press the magic button (virtually, of course). 

Sound about right, @kloydrti ?

**Comment by kloydrti** [comment]
Yes, it should be the Engagement Landing page markdown document in the engagement folder.

**Comment by RLC-DCPPC** [comment]
Well, I'll be darned! I believe this is complete.

@ACharbonneau, please review and let me know if it looks good.

**Comment by ACharbonneau** [comment]
LGTM thanks!
