### ISSUE TITLE
colors for website

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/public-website-content#21]
Hey @kloydrti I know you were exploring the idea of changing the color palette of the marketing website, and I was just curious whether we had a new one yet.

**Comment by kloydrti** [comment]
I'm working on a short style guide document, will link here when it's done (sometime tomorrow)

**Comment by kloydrti** [comment]
[Here is the document with colors and fonts](https://drive.google.com/file/d/1BhAbWB4cu6XVHi5Co0a9UnCg4b3mSF0J/view?usp=sharing). New logo files have also been uploaded to the CFDE Everyone > CFDE Logos and Templates drive folder (in the print and web folders).

**Comment by ACharbonneau** [comment]
cc: @RLC-DCPPC
