### ISSUE TITLE
Website tweaks before release

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/public-website-content#22]
There's a few things that need to be fixed on the demo version of the site before we release it:

- [x]  The Tools button doesn't link to anywhere
- [x] 'Tools' and 'Products' are both about the same content, but have different names. I think it should be 'Tools' for both
- [x] The whole right sidebar (Data Portal, Tech Doc, Tools, etc buttons) was only supposed to be on the *front* page of the site, as a quick navigator to other CFDE resources, but for some reason it's also on the "Engagement" page
- [x] I think it's really disorienting that all the pages *except* the front page have a prominent blue bar that separates the content from the header. It also makes having the big dark blue buttons on an otherwise white page very distracting. I'd like it to have the same bar on the front page so it looks like it goes with everything else. It could say "Indexing the Common Fund" or something like that. Something that tells me what this website is for
- [x] News and Events seems to be filler text. They should be links to actual content
- [x] Publications are HMP not CFDE. If we're going to do all related Publications that's fine, but realistically [This FAIRshake paper](https://www.sciencedirect.com/science/article/abs/pii/S240547121930345X) and [that paper Rick wrote](https://doi.org/10.1145/3311790.3396660) a couple months ago ("An Open Ecosystem for Pervasive Use of Persistent Identifiers", but link will not be live until after the conference in July) are much more 'CFDE'-y and should be there
- [x] The Portal button on marketing website becomes “Portal Available September 2020” (decided that a button is unnecessary until it actually goes somewhere; added the advertisement to Events section instead.)

**Comment by RLC-DCPPC** [comment]
Maybe an event could be "june 22, nih-cfde.org website relaunched"

**Comment by kloydrti** [comment]
Those changes have been made. I created markdown files in this repo for the news and publications so they can be edited easily. I also removed the data portal button for now and made "data portal coming in september" into a news item.

**Comment by ACharbonneau** [comment]
Cool :)

Just talked to Owen and have a couple more tweaks:

- For the front page text where I had you put "Indexing the CF", could we change it to "Common Fund Data Ecosystem Web Portal"? That might be too long and terrible. If it clearly is maybe just "CFDE Web Portal". Owen and I are still going back and forth on things, but so far I think we like that the most of our current ideas.

- Could we move the content of the "Resources" tab to be another option under "About" and rename it "Reports"

I've almost got some replacement text ready for the tools page about C2M2. It should be done in the next few days, but I think it's okay to replace it after release, so you don't need to wait on me when you're good.

**Comment by kloydrti** [comment]
I made those 2 changes. The longer home page title looks fine, it just wraps to two lines on mobile devices.

**Comment by RLC-DCPPC** [comment]
Add December Report under Reports

rewritten C2M2 and FAIR cookbook writeups to put unter Tools

remove C2M2 Guidelines link and the text it points to on the Engagement page. Replace with "Apply for Common Fund funding" with link to the FOA (https://commonfund.nih.gov/sites/default/files/Engagement_Opportunity_Announcement_1-29-20_FINAL_508.pdf
)

**Comment by kloydrti** [comment]
Everything is done except the C2M2 and FAIR cookbook writeups

**Comment by RLC-DCPPC** [comment]
Thanks, @kloydrti. This looks good.

So, please update nih-cfde.org with this content sometime today.

**Comment by kloydrti** [comment]
All the changes should be moved over. Let me know if you see something I missed.

**Comment by RLC-DCPPC** [comment]
This looks good to me, @kloydrti. We are live!

One small item is that once you click over to the technical documentation or the use case library, i don't see a way back. The "home" icons on those pages leave you on those sites. Since they open in new tabs, that is not a huge problem. Maybe links back to the public site could be added to those sites? What do you think, @ACharbonneau ?

**Comment by ACharbonneau** [comment]
I can add links back

**Comment by kloydrti** [comment]
@ACharbonneau The FAIR cookbook page is now live under Tools
