### ISSUE TITLE
Color scheme/Logo

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/public-website-content#26]
The new wireframes changed the website colors slightly, so now the logo sort of melts into the background but is also somewhat the wrong color. 

Secondarily, the websites are now using different color schemes, but they should all agree.

I'm not sure exactly how to fix the logo issue. wireframe image so you can see the problem:

[CFDE Wireframes DRAFT - 2 color treatments.pdf](https://github.com/nih-cfde/public-website-content/files/5411307/CFDE.Wireframes.DRAFT.-.2.color.treatments.pdf)

Do we need Katie to re-color the logo? Do we want to not use that blue in the headers? Something else? 

@jrchudy @kloydrti @RLC-DCPPC @victor73

**Comment by kloydrti** [comment]
There is a [white version of the logo](https://drive.google.com/file/d/1zGTP-YZlPILYxwSscyu6fkZkHghwrpZ0/view?usp=sharing) or a [color version with a white outline](https://drive.google.com/file/d/16QV9Wnxk9p-kXEoD6iBlA32ALx8L8B_D/view?usp=sharing). Either would stand out against the blue background. The blue should be #0355ab - other colors can be found in the [style guide](https://drive.google.com/file/d/1BhAbWB4cu6XVHi5Co0a9UnCg4b3mSF0J/view?usp=sharing).

**Comment by ACharbonneau** [comment]
Sorry, I missed an upload doc and made it confusing.

@kloydrti we gave the people who made wireframes for the portal your style guide. They came back with slightly different color suggestions. What I'm trying to do is figure out which we're going with and how to go about making everything match/look good.

the style guide they suggested is:
[CFDE Wireframes DRAFT - New Colors and Spacing.pdf](https://github.com/nih-cfde/public-website-content/files/5411783/CFDE.Wireframes.DRAFT.-.New.Colors.and.Spacing.pdf)

**Comment by ACharbonneau** [comment]
@kcamloyd This can go live asap

**Comment by kloydrti** [comment]
This is live.
