### ISSUE TITLE
Private layer webpage content

### ISSUE THREAD

**Issue by abhijna** [nih-cfde/public-website-content#27]
Hi @kloydrti and @ACharbonneau ,

Here's the content for the two private pages on the public website.

# Welcome page

Welcome to the Common Fund Data Ecosystem (CFDE) Coordination Center (CC)!

The CFDE-CC is an NIH effort to identify and solve issues that inhibit data access and reuse across NIH Common Fund programs. The Ecosystem is the Coordination Center plus all of the Common Fund Programs who participate. The ultimate goal of the CFDE is for the data to be more usable and useful both within a program’s own data and among datasets from multiple programs. By connecting the data and making them more accessible, the CFDE is intended to enable novel scientific research that was not possible before, including hypothesis generation, discovery, and validation.

Please take a few mins to learn about the CFDE, its objectives, challenges and project proposals:

- [What the CFDE is about](https://cfde-welcome-to-cfde.readthedocs-hosted.com/en/master/General_Onboarding/AboutCFDE/)

- [How the CFDE is organized](https://cfde-welcome-to-cfde.readthedocs-hosted.com/en/master/General_Onboarding/CFDE_Organization/)

Here are a few resources that the CFDE provides:

- [CFDE Use Case Library](https://cfde-usecases.readthedocs-hosted.com/en/latest/)

- [CFDE Training Resources](https://cfde-training.readthedocs.io/en/latest/)

- [CFDE Organization Repository](https://github.com/nih-cfde/organization)

# DCC onboarding page

If you are a new Common Fund Program that received funding to participate in the Common Fund Data Ecosystem (CFDE), you are in the right place. As you've probably heard, the CFDE is made up of the Coordination Center (CC) plus all of the Common Fund Programs who participate. It is a large program that consists of multiple, interoperable, and parallel projects across many teams and timezones -- A lot happens at the CFDE!

On this page you can find a multitude of resources that are important and relevant to your CFDE experience. These resources will give you a [brief overview](https://drive.google.com/file/d/1BU0mlp5D3itf91NmKyll2Da5Ct-ZaEs2/view?usp=sharing) of the CFDE and help your CF Program (or DCC) [get onboarded](https://docs.google.com/document/d/1qg0OGEtKYsOP657ZHFu7W5IIYCX4Psx-_n8UPA93pAA/edit#heading=h.8dy9wkax2sv1). You will also find links to resources that will help us communicate better, as well as track projects and progress in a systematic way.

 - [CFDE Overview](https://drive.google.com/file/d/1BU0mlp5D3itf91NmKyll2Da5Ct-ZaEs2/view?usp=sharing)

 - [Onboarding Instructions](https://cfde-welcome-to-cfde.readthedocs-hosted.com/en/master/)

 - [DCC Onboarding Resources](https://docs.google.com/document/d/1qg0OGEtKYsOP657ZHFu7W5IIYCX4Psx-_n8UPA93pAA/edit#heading=h.8dy9wkax2sv1)

 - Zenhub overview:

    - [Deliverables as Epics Tutorial](https://github.com/nih-cfde/organization/blob/master/projectmanagement/AddingIssuesToEpics.md)

    - [Expanded Work plan information](https://docs.google.com/document/d/1qg0OGEtKYsOP657ZHFu7W5IIYCX4Psx-_n8UPA93pAA/edit?usp=sharing)

    - [Zenhub Browser Extensions](https://www.zenhub.com/extension)

If you need any help during this process, please feel free to (contact us)[insert email here]

**Comment by kloydrti** [comment]
This content is now in 2 files (cfde-member-welcome.md and dcc-orientation.md) in this repo. Any updates to those files will automatically be pushed to the site.

Where it says "insert email here" for the dcc orientation I made a guess and used autohelp+int+851+6545985337373134556@CFDE.groups.io.

**Comment by kloydrti** [comment]
Am I right in remembering that people who are onboarded only to the website (the new "subscriber" role) should not see the dcc onboarding page?

**Comment by ACharbonneau** [comment]
correct :)
