### ISSUE TITLE
New CFDE resource pgs for Engagement section

### ISSUE THREAD

**Issue by marisalim** [nih-cfde/public-website-content#29]
Hi @kloydrti and @ACharbonneau 

I made new pages for the [Engagement](https://www.nih-cfde.org/engagement/) section of the public website. We'd like to do a bit of reorganizing so that the layout matches the [Tools](https://www.nih-cfde.org/tools/) page, where there's a landing page with "Read more" links to short blurbs about the resource.

I made markdown files on this branch: https://github.com/nih-cfde/public-website-content/tree/r03-resources/engagement

The idea is to start at the [landing page](https://github.com/nih-cfde/public-website-content/blob/r03-resources/engagement/engagement-landing.md) and then:

- (Meta-text) -> click -> (new page link)
- Engagement opportunities for Common Fund Programs -> click 'Read more'  -> [opportunities blurb; this is on the current landing pg](https://github.com/nih-cfde/public-website-content/blob/r03-resources/engagement/engagement-opportunities.md)
- Training Resources -> click 'Read more' -> [training blurb](https://github.com/nih-cfde/public-website-content/blob/r03-resources/engagement/engagement-training.md)
- Use Case Library -> click 'Read more' -> [UCL blurb](https://github.com/nih-cfde/public-website-content/blob/r03-resources/engagement/engagement-UCL.md)
- Events and Helpdesks -> click 'Read more' -> [CP/working groups/help desk blurbs](https://github.com/nih-cfde/public-website-content/blob/r03-resources/engagement/engagement-events-help.md)

I have a blurb for the CFDE portal, but will wait to post since the portal is not ready to be advertised.

Let me know if you need more info/reformatting, otherwise feel free to edit the files!

**Comment by marisalim** [comment]
@kloydrti If possible, we'd like these resources to be available to share with NIH R03 awardees by next Tuesday, Feb 16th. Please let me know if you'll need more time!

**Comment by kloydrti** [comment]
@marisalim I can get it done by then. I'll let you know when everything is up.

**Comment by marisalim** [comment]
@kloydrti awesome, thank you!

**Comment by kloydrti** [comment]
I merged all of the content onto the Master branch. If you edit the content on a separate branch in the future, it must be merged into Master before the changes will show up on the site.
All four pages have been published. I made up the icons, so if you want any changes to those just let me know.

**Comment by ACharbonneau** [comment]
Is it on production? All I see at engagement is the title

**Comment by kloydrti** [comment]
Whoops, I forgot to push it to production. It's all there now!

**Comment by marisalim** [comment]
It looks great, thanks @kloydrti!

**Comment by marisalim** [comment]
these pages were added!
