### ISSUE TITLE
waitlist for (workshop) events

### ISSUE THREAD

**Issue by marisalim** [nih-cfde/public-website-content#35]
Hi @kloydrti - another booking system request! Is there a waitlist function? 

Right now, once the registration max is hit, the registration closes with a message that the event is fully booked. Since some people cancel or don't show up, we'd like a waitlist + message we could customize for people on the waitlist.

**Comment by ACharbonneau** [comment]
Possible solution: When an event is fully booked, the text changes to say something like 'fully booked- email support@cfde.atlassian.net to be put on the waitlist'

**Comment by kloydrti** [comment]
The "Fully booked" message has been changed.

**Comment by marisalim** [comment]
Hi @kloydrti - the message helps a bit (for the time being, can you change it to `email training@cfde.atlassian.net`), but we still have to keep track of the waitlist manually. 

Is it possible to have a waitlist on the website? I.e., if someone cancels, we can delete their booking and move someone from the waitlist automatically to an event spot. This would help us with managing the waitlist more effectively!

**Comment by kloydrti** [comment]
The email has been changed. There is no waitlist feature available for the events plugin.

**Comment by marisalim** [comment]
Ah, that's too bad :( thanks for changing the email @kloydrti!
