### ISSUE TITLE
Make URL of member pages not their email

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/public-website-content#36]
The URL of my member page is https://www.nih-cfde.org/members/acharucdavis-edu/

so literally just my email with the punctuation taken out. Is it possible to change what field gets used for the URL generation? I'm happy to add a new step to onboarding to make an ID field that isn't an email if needed.

**Comment by marisalim** [comment]
i think this got fixed - the url now looks like https://www.nih-cfde.org/members/396c5b5ad1bbcb8c/
