### ISSUE TITLE
Ability to create workshop template and view past workshops

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/public-website-content#37]
Currently in the Edit Events tab, a user with permissions only sees the upcoming workshops. It would be beneficial to be able to view the past workshops. 
On the same note it would be useful to have the ability to create a template from current or past workshop and replicate that with the ability to modify minor details before posting. 
@kloydrti - Can you help with the implementation ?

**Comment by raynamharris** [comment]
the ability to see past workshops exists, yea :)
