### ISSUE TITLE
Multi day events should show on all days in calendar

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/public-website-content#38]
The CFDE program meeting event page suggests it is on two consecutive days: https://www.nih-cfde.org/events/cfde-program-meeting/

But in the calendar for May, the event only shows up on the first date (10th) but not on 11th.
Ideal behavior: any multi day event should show up on all dates on the calendar with the same title automatically. 

@kloydrti - help ?

**Comment by kloydrti** [comment]
I just had to change a setting. Multi-day events should show up on all days now.
