### ISSUE TITLE
Add CFDE internal training resources to the public site for members

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/public-website-content#40]
Hi @kloydrti - We are reorganizing the [CFDE training website ](https://training.nih-cfde.org/en/latest/) and wanted to move most of the contents in the CFDE Internal Training tab to the public website. 

I moved the necessary files and images to a folder within resources folder on the repo and currently in this branch: https://github.com/nih-cfde/public-website-content/tree/scanchi-member-resources

However, I don't see the render of the files in the resources folder on the website. If that is not the correct folder, let me know and I can update it. The idea is to replicate how it looks in the training website [with a landing page and links to individual lesson](https://training.nih-cfde.org/en/latest/CFDE-Internal-Training/).

**Comment by kloydrti** [comment]
I will need to build the pages first. I can get that done by next Tuesday.

**Comment by kloydrti** [comment]
@s-canchi is this content supposed to be available to everyone or just people who have been onboarded to CFDE?

**Comment by ACharbonneau** [comment]
It doesn't have to be private. If it fits in the public part it's fine to be there

**Comment by kloydrti** [comment]
The new content is there. The screencasts don't work, but we could add a regular video file or use the embed code if the screencasts are hosted on asciinema.org.

**Comment by s-canchi** [comment]
For our website, I had to integrate the asciinema player to use the local screencast files. Is that possible in Wordpress ? Details on javascript here: https://asciinema.org/docs/embedding

If not, I can plan to upload them to asciinema. org and provide the embed code.

**Comment by kloydrti** [comment]
The javascript tags on that site reference the file source on asciinema.org. The embed doesn't work with the .cast files that were uploaded to this repo.

**Comment by s-canchi** [comment]
Right. But it also possible to include the asciinema player locally into the site: https://blog.asciinema.org/post/html5-element/

Here is the file (asciinema-player.js) in our training repo: https://github.com/nih-cfde/training-and-engagement/tree/stable/docs/javascripts

And this is the syntax we use for playing local files: 
```
<asciinema-player src="../mime_supplementary_files/file_screencast.cast" speed="2" theme="tango" font-size="medium" cols="60" rows="15" poster="data:text/plain,\x1b[1;37mTerminal Vidlet for file"></asciinema-player>
```

I am wondering if this can be replicated in Wordpress ?

**Comment by kloydrti** [comment]
I tried that as well as the wordpress plugins available. I got the player to appear but it wouldn't load the content. I think it's a problem with the wordpress file structure that can't be worked around.

**Comment by s-canchi** [comment]
Thank you for trying! I will plan to upload these the asciinema website and post the embed codes in this issue.

**Comment by s-canchi** [comment]
Providing embedding code for all screencasts:

- file screencast: <script id="asciicast-eiT7iUpqhY7mikZoOWiTZuwyx" src="https://asciinema.org/a/eiT7iUpqhY7mikZoOWiTZuwyx.js" async speed="2" theme="tango" font-size="medium" cols="60" rows="15" poster="data:text/plain,\x1b[1;37mTerminal Vidlet for file"></script>
- mimetype screencast: <script id="asciicast-rK9TgGIWalHEXmGxK9OC4F1ni" src="https://asciinema.org/a/rK9TgGIWalHEXmGxK9OC4F1ni.js" async speed="2" theme="tango" font-size="medium" cols="60" rows="15" poster="data:text/plain,\x1b[1;37mTerminal Vidlet for mimetype"></script>
- xdg-utils screencast: <script id="asciicast-yNQHHN1PnyDWte8ZvOAPRwTvm" src="https://asciinema.org/a/yNQHHN1PnyDWte8ZvOAPRwTvm.js" async speed="2" theme="tango" font-size="medium" cols="60" rows="15" poster="data:text/plain,\x1b[1;37mTerminal Vidlet for xdg-mime"></script>
- siegfried screencast: <script id="asciicast-FU8AMGZ43NoUXmjBup2bCgyin" src="https://asciinema.org/a/FU8AMGZ43NoUXmjBup2bCgyin.js" async speed="2" theme="tango" font-size="medium" cols="60" rows="15" poster="data:text/plain,\x1b[1;37mTerminal Vidlet for siegfried"></script>

Let me know if these work!

**Comment by kloydrti** [comment]
Those work great! They're all published.
