### ISSUE TITLE
event calendar tags?

### ISSUE THREAD

**Issue by marisalim** [nih-cfde/public-website-content#45]
Is there a way to add tags to i.e., all workshop or working group events so they're easier to find quickly in the "Edit Events" page? When I use the "Search Events" search box, it doesn't seem to be filtering by words in event titles (i.e., searching for "demo" brings up a lot of events that don't have "demo" in their title).

**Comment by kloydrti** [comment]
The search feature is fixed now. There are no tag or categories capabilities, but the search will now match any word in the title or description.
