### ISSUE TITLE
Widget to embed events calendar in training website: Asking for help

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/public-website-content#47]
We currently list individual workshops (past only) on our [training website home page](https://training.nih-cfde.org/en/latest/). But since the content on the website is governed by release cycles, we cannot automate the workshop list to be current. What we would like to have is the [events calendar](https://www.nih-cfde.org/events/) being embded as a widget in the home page to populate with the latest information.

This is an example site with one such calendar: https://hubmapconsortium.org

The public site uses Wordpress while our training site uses MkDocs specially [MkDocs-material theme ](https://squidfunk.github.io/mkdocs-material/). We found a few options for widgets to embed within Wordpress sites or to communicate between Wordpress sites but not much between Wordpress and a non Wordpress site. 

@kloydrti - do you know of any external widgets or code that can achieve this ? or can you point us to the right direction to test some solutions ?

**Comment by s-canchi** [comment]
Can you also point out to what calendar widget/plugin is being used in the public site ?

**Comment by ACharbonneau** [comment]
@s-canchi Please check issue #49
