### ISSUE TITLE
Change title

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/public-website-content#48]
Hey @kloydrti quick change. Could you update this to say "Common Fund Data Ecosystem Home" and not "Common Fund Data Ecosystem Web Portal" 

Users are finding it really confusing

![image](https://user-images.githubusercontent.com/1719360/114230604-5a33bd00-9947-11eb-98fa-6beb9d7924ab.png)

**Comment by kloydrti** [comment]
Done.
