### ISSUE TITLE
update https://www.nih-cfde.org/product/cfde-c2m2/

### ISSUE THREAD

**Issue by abradyIGS** [nih-cfde/public-website-content#50]
language needs to be brought current with https://docs.nih-cfde.org/en/latest/c2m2/draft-C2M2_specification/

fixes include but are not limited to

* remove Levels language
* change out old (Level 0) graphic

subpages linked off the issue-subject URL are also in need of updating.

**Comment by ACharbonneau** [comment]
does anyone @nih-cfde/training have some time to fix up these pages?

**Comment by josesanchez1815** [comment]
Hi! I have some questions about this? When you say you would like to change the old (Level 0) graphic, is it to be replaced with another image or just taken out entirely?

I have another question for the "remove Levels Language" fix.
https://www.nih-cfde.org/product/c2m2-how-it-works/
https://www.nih-cfde.org/product/c2m2-model-levels-usage/
The previous two pages are comprised of "Levels Language." Are they to be removed or replaced?

**Comment by ACharbonneau** [comment]
So. The model didn't really change but we stopped calling it 'level 0' or 'level 1' or 'level 2'. It's just 'the C2M2 model' now. So, we need someone to go through and make it stop saying 'level whatever' and just call it the C2M2 model. The old picture (that says level in it) needs to be replaced with the new picture that doesn't say level

**Comment by josesanchez1815** [comment]
![image](https://user-images.githubusercontent.com/62918474/119180573-4f2f7a80-ba25-11eb-9b96-2736f7838a32.png)
 
Where can I find this image (I used a snipping tool for this image.) Where do I find this image? I tried looking in this repository, but I cannot seem to find it. I've looked at the following links and am unsure of how to replace this image.

https://github.com/nih-cfde/public-website-content/blob/master/products/product-C2M2.md

**Comment by josesanchez1815** [comment]
Would I be allowed to get rid of this [page](https://github.com/nih-cfde/public-website-content/blob/master/products/C2M2-how-it-works.md)? This page is primarily all levels language unless you would like the text be replaced with some information from the technical documentation

**Comment by josesanchez1815** [comment]
@ACharbonneau I need help locating where in the repo I need to go to remove this image. https://www.nih-cfde.org/product/cfde-c2m2/

 I found the text on this page in this link https://github.com/nih-cfde/public-website-content/blob/master/products/product-C2M2.md but I am unaware where the Levels Image comes from.

**Comment by marisalim** [comment]
@ACharbonneau there are 2 edits that need to happen for the nih-cfde.org site:

1. c2m2 image

The complete c2m2 image that does *not* have "level" in it is here: https://github.com/nih-cfde/c2m2/blob/master/draft-C2M2_ER_diagrams/C2M2.png

We could use a part of that image or the minimal submission c2m2 image here: https://github.com/nih-cfde/c2m2/blob/master/draft-C2M2_ER_diagrams/minimal_submission_example.png

It should go on these 2 pages of the nih-cfde.org website: 
- https://www.nih-cfde.org/tools/
- https://www.nih-cfde.org/product/cfde-c2m2/

2. c2m2 pages about levels

Jose has an open PR #54 to update 2 pages on the nih-cfde.org website that still talk about levels. maybe both pages should be deleted completely from the site?
- https://www.nih-cfde.org/product/c2m2-how-it-works/ 
- https://www.nih-cfde.org/product/c2m2-model-levels-usage/

**Comment by ACharbonneau** [comment]
yup just disappear them

**Comment by marisalim** [comment]
@ACharbonneau - those pages are now deleted. just need to update the c2m2 image. something like this? it's part of the full c2m2 diagram --


<img width="917" alt="c2m2_website_snapshot" src="https://user-images.githubusercontent.com/5659802/124036090-521d7380-d9b2-11eb-9f61-c9b11610bbdd.png">

**Comment by ACharbonneau** [comment]
yep, I'm working on it.

**Comment by ACharbonneau** [comment]
It looks like you made the content of the page delete but not the page itself, so I have to figure out how that works too :/

**Comment by marisalim** [comment]
Huh, that's odd, the PR said the files for those pages were deleted 😞

**Comment by ACharbonneau** [comment]
Yeah. It's definitely a thing i have to switch in wordpress, I just need to make sure I'm sure I know what I'm doing before I delete stuff/change things.

**Comment by lance1572** [comment]
Looks like the pages

https://www.nih-cfde.org/product/c2m2-how-it-works/
https://www.nih-cfde.org/product/c2m2-model-levels-usage/

Are still up but with no content. I will turn them off so they do not show. I'm guessing that needs to be done from this thread.

**Comment by jacko13** [comment]
Hello @ACharbonneau. Just wanted to help progress this. I'm happy to update the image on the the two pages that it appears on. As you mentioned a while back, the original images are no longer available. I did see a variety of C2M2 diagrams. I can also produce a new one based on snippets of other images. Could you please let me know how we can proceed with this one? Thank you.

**Comment by ACharbonneau** [comment]
If you could make some new snippets that would be great. The source image to use is https://github.com/nih-cfde/c2m2/blob/master/ER_diagrams/C2M2.png

**Comment by jacko13** [comment]
![C2M2-snippet](https://user-images.githubusercontent.com/9009847/153671847-aa22afd8-e25f-4fcb-a5dc-f282edeb6050.png)
Definitely can make snippets of that image. I wasn't sure if I should just still include only the **file** and the **namespace** entities, or whether you wanted more than that. I wasn't sure if I should be going by the "minimal submission" and exactly what that might be. The **file** entity has a lot of attributes - I can weed some of the non-essential ones out as needed.

Can you please review the update and let me know whether to rework and what you'd like? Thank you.

**Comment by ACharbonneau** [comment]
I think whatever looks nice is fine. The image is mostly to make the page more interesting rather than to have them learn the model
