### ISSUE TITLE
Update helpdesk email

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/public-website-content#58]
Hi @jacko13 

When the help form on the website was originally set up, we didn't have an official helpdesk yet, so the email is going to autohelp@CFDE.groups.io which is just me. I need that form to instead send to support@cfde.atlassian.net

**Comment by jacko13** [comment]
![Issue-58-Contact-Form](https://user-images.githubusercontent.com/9009847/158450665-16217867-4d49-4a79-9836-7c075f79b898.png)
Just confirming - is this the form you're referring to - that you'd like the email changed for?

**Comment by ACharbonneau** [comment]
yup

**Comment by jacko13** [comment]
Yes - thought so, just being careful. I will change this now.

**Comment by jacko13** [comment]
This is changed both on Development and in Production.
I was hesitant to send a test message, but can if you like. Let me know and then we can close this one out.

**Comment by jeremywalter** [comment]
So... now I'm seeing all the form stuff coming into helpdesk, but what I really want is just a straight link to support@cfde.atlassian.net -- this would give me the power to block and filter some of what is incoming... as long as it is going through the website form we're stuck having to process every ticket even if it's the same account sending the same dumb thing every day. I'm not sure if there is a better alternative, but that is the solution that made the most sense to me. 

If no one objects or thinks it's a bad idea, I would really just like 'Contact' to be "mailto:support@cfde.atlassian.net" or similar... no forms to fill out.

**Comment by jeremywalter** [comment]
I don't have any strong opinions on how it is done, I just want it simple and I want everything to go direct to support so we can filter. If we get a lot of hits/requests for specific contacts we can arrange that, but those resources are already available for CFDE members. Right now I believe this is a less is more situation. We have very little traffic and if it picks up we can pivot IMO.

**Comment by jacko13** [comment]
@raynamharris and I swapped some notes about this. Thanks for sharing your feedback and sharing your ideas @jeremywalter .

A possible solution (chatted with @raynamharris ) could be:
Decommission the Contact Us FORM and put a general replacement link to email on it - with more general supporting text.
Keep the Contact Us option that goes to Jira for people who have logged in.

How does this sound?

**Comment by ctb** [comment]
Sounds good. Can this be done soon, please?

thanks!

**Comment by jeremywalter** [comment]
Update?

**Comment by jeremywalter** [comment]
I have removed the form and replaced with text to e-mail helpdesk directly for more QC.

This is the code implementation for the form that I'm removing from Pages - Contact:
https://www.nih-cfde.org/wp-admin/post.php?post=1000000092&action=edit&classic-editor

[vc_row][vc_column][vc_raw_html]JTNDZGl2JTIwY2xhc3MlM0QlMjJpbnRybyUyMiUzRSU1Qm1kX2dpdGh1YiUyMHRva2VuJTNEMjZmZTg3ZTg4YjMxM2Q1MjQwMzYzYmNiMWMxYzg5ZjgxMmQxYTc5MyUyMHVybCUzRGh0dHBzJTNBJTJGJTJGZ2l0aHViLmNvbSUyRm5paC1jZmRlJTJGcHVibGljLXdlYnNpdGUtY29udGVudCUyRmJsb2IlMkZtYXN0ZXIlMkZjb250YWN0LWludHJvLm1kJTVEJTNDJTJGZGl2JTNF[/vc_raw_html][vc_separator color="custom" accent_color="#e6e6e6"][/vc_column][/vc_row][vc_row][vc_column offset="vc_col-lg-offset-3 vc_col-lg-6 vc_col-md-offset-2 vc_col-md-8" bb_tab_container=""][bbrp_shortcode_import shortcode="JTVCZm9ybWluYXRvcl9mb3JtJTIwaWQlM0QlMjIxMDAwMDAxMDE1JTIyJTVE"][/vc_column][/vc_row]
