### ISSUE TITLE
Please add C2M2 guidelines document

### ISSUE THREAD

**Issue by owhite** [nih-cfde/public-website-content#6]
The following is a link that contains a description of the purpose of the CFDE Data Asset Specification, the Data Asset Manifest, along with information about staffing required to support generation of same. 

https://docs.google.com/document/d/1N2LqcfuOUVeqQn_NwkTPWYvZO7eEQCQsZa-zYaXPIic/edit

**Comment by ACharbonneau** [comment]
@kcamloyd Can you add this to the Engagement page? The new pages I made while RTI was on hiatus don't have templates to add to

**Comment by owhite** [comment]
Suggested location would be under  “Engagement”: 

https://nih-cfde.org/engaging-common-fund-data-coordinating-centers/

**Comment by ACharbonneau** [comment]
This one is ASAP. DCCs are using these guidelines for their proposals due 3/15.

(We also emailed it to them, so it's not the end of the world if it takes a couple days)

**Comment by mrathbun-rti** [comment]
@kloydrti Due 3/5, 3/6 latest

**Comment by kloydrti** [comment]
C2M2 guidelines are live at [C2M2 Guidelines](https://nih-cfde.org/engagement_page/c2m2-guidelines/) under the Engagement section. Both engagement pages are now sourced from markdown files in the Engagement folder of this repository.
