### ISSUE TITLE
add partner page

### ISSUE THREAD

**Issue by raynamharris** [nih-cfde/public-website-content#65]
I have created a new document called [partners.md](https://github.com/nih-cfde/public-website-content/blob/master/partners/partners.md) (see #59) that needs to be added to the public website. 

I think it would be great to add a page called "Partners" under the "About" tab on the home page. 

![Screen Shot 2022-07-20 at 12 40 53 PM](https://user-images.githubusercontent.com/7544197/180068019-dff3186f-5378-4f61-8bb3-671fa1663560.png)

@jacko13 is this something you can help with? Thanks

**Comment by jacko13** [comment]
Hi @raynamharris . Yes. I can help with that. I'll take a look now. Will follow up when it's live.

**Comment by jacko13** [comment]
Hi @raynamharris. I've put this on the CFDE production site. Can you please review and let me know whether it's good.

https://www.nih-cfde.org/partners/

I placed access to this page under the About tab - positioned in alphabetical order.

Thank you.

**Comment by raynamharris** [comment]
Done. Thank you @jacko13 

![Screen Shot 2022-07-21 at 1 33 29 PM](https://user-images.githubusercontent.com/7544197/180310123-e1957a59-e1ba-442c-b10c-2104c4b58b5a.png)
