### ISSUE TITLE
Events page changes

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/public-website-content#7]
Please:

- [x] move current event info to some kind of 'past events' location
- [x] make this page have some sort of brief, forward looking events info
- [x] have the brief info link/open into more detailed information about a specific event
- [x] add the two upcoming Cross pollination events (May 13-14, 2020 and September 9-10, 2020)
- [x] make it so we can host registration for those two events on this site. Natively or as an eventbrite (or whatever) plug in is fine

**Comment by mrathbun-rti** [comment]
@kloydrti due date is 3/9

**Comment by kloydrti** [comment]
I've made some changes to the staging site that I can go through during our meeting tomorrow. Basically I can't find a free option to handle event registration directly in Wordpress, but if you're ok with continuing to use eventbrite, then we can easily embed the eventbrite registration into the site.

**Comment by kloydrti** [comment]
Basic events are now published on the site. Can add Eventbrite / registration information when it becomes available.
