### ISSUE TITLE
Resources page

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/public-website-content#8]
Please:

- [ ] Add the December report https://drive.google.com/drive/u/1/folders/1d-tq_-2ifMW9784ycwLtHO7EiGYYZH0z
- [ ] update all three reports to include their figshare DOIs:
  - Dec: https://figshare.com/articles/2019-December_CFDE_AssessmentReport_pdf/11592936
  - Oct: https://figshare.com/articles/2019-October_CFDE_AssessmentReport_pdf/10261055
  - July: https://figshare.com/articles/2019-July_CFDE_AssessmentReport_pdf/9588374

**Comment by mrathbun-rti** [comment]
@kloydrti due date is 3/9

**Comment by kloydrti** [comment]
December report and figshare links are now live on the Resources page. The resources side menu is ordered alphabetically - let me know if you want it changed
